{{- if .Values.persistence.enabled }}
{{- $existing := (lookup "v1" "PersistentVolumeClaim" .Release.Namespace (printf "%s-data" (include "evan-proxy.fullname" .))) }}
{{- if not $existing }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "evan-proxy.fullname" . }}-data
  labels:
    {{- include "evan-proxy.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
{{- end }}
{{- end }}
