{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "evan-proxy.fullname" . }}
  labels:
    {{- include "evan-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  ADMIN_USER: {{ .Values.admin.user | quote }}
  ADMIN_PASSWORD: {{ .Values.admin.passwordHash | quote }}
{{- end }}
