{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "evan-proxy.fullname" . }}
  labels:
    {{- include "evan-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  users.json: |
    {
      "users": [
        {{- $last := sub (len .Values.proxyUsers) 1 }}
        {{- range $i, $user := .Values.proxyUsers }}
        {"username": {{ $user.username | quote }}, "password": {{ $user.password | quote }}}{{- if ne $i (int $last) }},{{- end }}
        {{- end }}
      ]
    }
  ADMIN_USER: {{ .Values.admin.user | quote }}
  ADMIN_PASSWORD: {{ .Values.admin.passwordHash | quote }}
{{- end }}
