apiVersion: v1
kind: Service
metadata:
  name: {{ include "evan-proxy.fullname" . }}
  labels:
    {{- include "evan-proxy.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    {{- if .Values.service.exposeAdmin }}
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
    {{- end }}
    {{- $min := .Values.proxy.userPortMin | int }}
    {{- $max := .Values.proxy.userPortMax | int }}
    {{- range $p := untilStep $min (add1 $max | int) 1 }}
    - name: user-{{ $p }}
      port: {{ $p }}
      targetPort: {{ $p }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "evan-proxy.selectorLabels" . | nindent 4 }}
